name: Scott Pruett
favicon: null
layout_spectrum: 0.25397
typography_spectrum: 0.86211
title: scott.pruett.co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#828282'
    - '#bfbfbf'
    - '#4e4e4e'
    - '#e2e2e2'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
