name: Scott
favicon: null
layout_spectrum: 0
typography_spectrum: 0.66634
title: scott.pruett.co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#828282'
    - '#bfbfbf'
    - '#4e4e4e'
    - '#e2e2e2'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
